package me.legrange.panstamp.gui.network;

import java.awt.CardLayout;
import java.util.Stack;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import me.legrange.panstamp.gui.config.IntegerDocument;
import me.legrange.panstamp.gui.model.DataModel;

/**
 *
 * @author gideon
 */
public class NetworkAddDialog extends javax.swing.JDialog {
    
    private enum State { SELECT_TYPE, SELECT_COM, SELECT_TCP, END; };

    /**
     * Creates new form PanStampSettingsDialog
     */
    public NetworkAddDialog(java.awt.Frame parent, DataModel model) {
        super(parent, true);
        this.model = model;
        initComponents();
        state.push(State.SELECT_TYPE);
        applyState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        outerSplitPane = new javax.swing.JSplitPane();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        innerSplitPane = new javax.swing.JSplitPane();
        contentPanel = new javax.swing.JPanel();
        createNetworkPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        configTcpPanel = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        tcpPortLabel = new javax.swing.JLabel();
        tcpPortTextField = new javax.swing.JTextField();
        hostTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        selectTypePanel = new javax.swing.JPanel();
        serialRadioButton = new javax.swing.JRadioButton();
        tcpRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        configSerialPanel = new javax.swing.JPanel();
        portLabel = new javax.swing.JLabel();
        speedLabel = new javax.swing.JLabel();
        speedComboBox = new javax.swing.JComboBox();
        portComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Network");
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        outerSplitPane.setBorder(null);
        outerSplitPane.setDividerSize(0);
        outerSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel2.setText("Add a PanStamp network:");
        headerPanel.add(jLabel2);

        outerSplitPane.setRightComponent(headerPanel);

        innerSplitPane.setBorder(null);
        innerSplitPane.setDividerSize(0);
        innerSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        contentPanel.setLayout(new java.awt.CardLayout());

        createNetworkPanel.setName("create-network-panel"); // NOI18N

        jLabel3.setText("Create netwotk");

        javax.swing.GroupLayout createNetworkPanelLayout = new javax.swing.GroupLayout(createNetworkPanel);
        createNetworkPanel.setLayout(createNetworkPanelLayout);
        createNetworkPanelLayout.setHorizontalGroup(
            createNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNetworkPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addContainerGap(736, Short.MAX_VALUE))
        );
        createNetworkPanelLayout.setVerticalGroup(
            createNetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNetworkPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        contentPanel.add(createNetworkPanel, "create-network-panel");

        configTcpPanel.setName("config-tcp-panel"); // NOI18N

        hostLabel.setText("Host name/address:");
        hostLabel.setToolTipText("");

        tcpPortLabel.setText("TCP Port:");
        tcpPortLabel.setToolTipText("");

        tcpPortTextField.setColumns(4);
        tcpPortTextField.setDocument(new IntegerDocument(0,255));
        tcpPortTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpPortTextFieldActionPerformed(evt);
            }
        });
        tcpPortTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tcpPortTextFieldPropertyChange(evt);
            }
        });

        hostTextField.setColumns(4);
        hostTextField.setDocument(new IntegerDocument(0,255));
        hostTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hostTextFieldPropertyChange(evt);
            }
        });

        jLabel5.setText("Enter hostname and TCP port");

        javax.swing.GroupLayout configTcpPanelLayout = new javax.swing.GroupLayout(configTcpPanel);
        configTcpPanel.setLayout(configTcpPanelLayout);
        configTcpPanelLayout.setHorizontalGroup(
            configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTcpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(configTcpPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(configTcpPanelLayout.createSequentialGroup()
                        .addGroup(configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostLabel)
                            .addComponent(tcpPortLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcpPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        configTcpPanelLayout.setVerticalGroup(
            configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTcpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostLabel)
                    .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configTcpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcpPortLabel)
                    .addComponent(tcpPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.add(configTcpPanel, "config-tcp-panel");

        selectTypePanel.setName("select-type-panel"); // NOI18N

        typeButtonGroup.add(serialRadioButton);
        serialRadioButton.setSelected(true);
        serialRadioButton.setText("Serial Network");
        serialRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialRadioButtonActionPerformed(evt);
            }
        });

        typeButtonGroup.add(tcpRadioButton);
        tcpRadioButton.setText("TCP/IP Network");

        jLabel1.setText("Select the type of PanStamp network to create");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout selectTypePanelLayout = new javax.swing.GroupLayout(selectTypePanel);
        selectTypePanel.setLayout(selectTypePanelLayout);
        selectTypePanelLayout.setHorizontalGroup(
            selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addGroup(selectTypePanelLayout.createSequentialGroup()
                        .addGroup(selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcpRadioButton)
                            .addComponent(serialRadioButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        selectTypePanelLayout.setVerticalGroup(
            selectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serialRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcpRadioButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contentPanel.add(selectTypePanel, "select-type-panel");

        configSerialPanel.setName("config-serial-panel"); // NOI18N

        portLabel.setText("Port:");
        portLabel.setName("config-serial-panel"); // NOI18N

        speedLabel.setText("Speed (bps):");
        speedLabel.setName("config-serial-panel"); // NOI18N

        speedComboBox.setModel(speedListModel());
        speedComboBox.setName("config-serial-panel"); // NOI18N
        speedComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedComboBoxActionPerformed(evt);
            }
        });

        portComboBox.setModel(portListModel());
        portComboBox.setName("config-serial-panel"); // NOI18N
        portComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Select serial port and baud rate");

        javax.swing.GroupLayout configSerialPanelLayout = new javax.swing.GroupLayout(configSerialPanel);
        configSerialPanel.setLayout(configSerialPanelLayout);
        configSerialPanelLayout.setHorizontalGroup(
            configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configSerialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(configSerialPanelLayout.createSequentialGroup()
                        .addGroup(configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedLabel)
                            .addComponent(portLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(574, Short.MAX_VALUE))
        );
        configSerialPanelLayout.setVerticalGroup(
            configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configSerialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portLabel))
                .addGap(16, 16, 16)
                .addGroup(configSerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLabel)
                    .addComponent(speedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        contentPanel.add(configSerialPanel, "config-serial-panel");

        innerSplitPane.setLeftComponent(contentPanel);

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addGap(124, 124, 124)
                .addComponent(cancelButton)
                .addGap(5, 5, 5)
                .addComponent(finishButton))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextButton)
                        .addComponent(backButton))
                    .addComponent(cancelButton)
                    .addComponent(finishButton)))
        );

        innerSplitPane.setRightComponent(buttonPanel);

        outerSplitPane.setLeftComponent(innerSplitPane);

        getContentPane().add(outerSplitPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
           backward();
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        forward();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishButtonActionPerformed

    private void serialRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialRadioButtonActionPerformed

    private void tcpPortTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tcpPortTextFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tcpPortTextFieldPropertyChange

    private void hostTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hostTextFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_hostTextFieldPropertyChange

    private void tcpPortTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpPortTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcpPortTextFieldActionPerformed

    private void portComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portComboBoxActionPerformed
        //config.setPortName((String) portComboBox.getModel().getSelectedItem());
    }//GEN-LAST:event_portComboBoxActionPerformed

    private void speedComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedComboBoxActionPerformed
        //config.setPortSpeed((Integer) speedComboBox.getModel().getSelectedItem());
    }//GEN-LAST:event_speedComboBoxActionPerformed

    private void forward() {
        switch (getState()) {
            case SELECT_TCP :
            case SELECT_COM : 
                state.push(State.END);
                break;
            case SELECT_TYPE : 
                if (serialRadioButton.isSelected()) {
                    state.push(State.SELECT_COM);
                }
                else {
                    state.push(State.SELECT_TCP);
                }
        }
        applyState();
    }
    
    private void backward() {
        state.pop();
        applyState();
    }
    
    private void applyState() {
        backButton.setEnabled(getState() != State.SELECT_TYPE);
        nextButton.setEnabled(getState() != State.END);
        finishButton.setEnabled(getState() == State.END);
        // select content for wizard based on state
        JPanel content = null;
        switch (getState()) {
            case SELECT_TYPE :
                content = selectTypePanel;
                break;
            case SELECT_TCP : 
                content = configTcpPanel;
                break;
            case SELECT_COM : 
                content = configSerialPanel;
                break;
            case END : 
                content = createNetworkPanel;
                break;
            default : return;
        }
        CardLayout clo = (CardLayout) contentPanel.getLayout();
        clo.show(contentPanel, content.getName());
    }
    
    private State getState() {
        return state.peek();
    }
 
    private ComboBoxModel<String> portListModel() {
        DefaultComboBoxModel<String> mod = new DefaultComboBoxModel<>();
        for (String port : model.getConfig().getPorts()) {
            mod.addElement(port);
            if (port.equals(model.getConfig().getPortName())) {
                mod.setSelectedItem(port);
            }
        }
        return mod;
    }

    private ComboBoxModel<Integer> speedListModel() {
        DefaultComboBoxModel<Integer> mod = new DefaultComboBoxModel<>();
        for (Integer speed : model.getConfig().getSpeeds()) {
            mod.addElement(speed);
            if (speed.equals(model.getConfig().getPortSpeed())) {
                mod.setSelectedItem(speed);
            }
        }
        return mod;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel configSerialPanel;
    private javax.swing.JPanel configTcpPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel createNetworkPanel;
    private javax.swing.JButton finishButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JSplitPane innerSplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton nextButton;
    private javax.swing.JSplitPane outerSplitPane;
    private javax.swing.JComboBox portComboBox;
    private javax.swing.JLabel portLabel;
    private javax.swing.JPanel selectTypePanel;
    private javax.swing.JRadioButton serialRadioButton;
    private javax.swing.JComboBox speedComboBox;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JLabel tcpPortLabel;
    private javax.swing.JTextField tcpPortTextField;
    private javax.swing.JRadioButton tcpRadioButton;
    private javax.swing.ButtonGroup typeButtonGroup;
    // End of variables declaration//GEN-END:variables
    private final DataModel model;
    private final Stack<State> state = new Stack<>();
    
}
